style: update normalize.css to 5.0.0
miraiken/web pull request #29
Opened 2017-02-05 16:32 UTC by yumetodo

use CDN

ref: #26 

@NishiCell デザインが変わっていないか確認したつもりですが、そちらでも確認をお願いします。

2017-02-06 10:53 UTC, celluloce requested changes
テーブルの行間・font-familyの問題点がありました。

2017-02-06 10:53 UTC, celluloce commented on common/css/style.css
> +}
/event/index.html にて、過去のイベントのテーブルの行間が詰まってますがこれはどういうことでしょうか？

2017-02-06 10:53 UTC, celluloce commented on common/css/style.css
> +}
``normalize.css``の13行目にて、line-heightが1.15になっております。

2017-02-06 10:53 UTC, celluloce commented on common/css/style.css
> +
``/event/2016/event_june/exhibition.html``において、font-familyを無効にしてみたところ何ら変化がありませんでした。
これは必要ないのでは？

2017-02-06 14:28 UTC, yumetodo commented on common/css/style.css
> +
Normalize.css v5.0.0では

```css
font-familiy: sans-serifl;
```

にフォールバックされてしまう。Windowsとかいうフォントがクソな世界のために必要である。

2017-02-06 14:28 UTC, yumetodo commented on common/css/style.css
> +}
あっ

2017-02-06 14:47 UTC, yumetodo commented on common/css/style.css
> +}
https://github.com/necolas/normalize.css/blob/5.0.0/normalize.css#L15
これか・・・。

2017-02-10 09:35 UTC, yumetodo commented on common/css/style.css
> +}
どうしようかな・・・。Windowsだとそこまでもともと間延びしてなかったんだよなぁ・・・。

もうすこしpaddingを取る方向にするかな・・・。

2017-02-10 11:27 UTC, yumetodo commented
@NishiCell 表の行間問題、``normalize.css``の``line-height``が原因ではあるんだが、これがないとWindowsとLinuxで全然違う見た目になってしまう模様。
したがって、``td``タグに``padding``を設定することにした。

これでいいだろうか・・・？

2017-02-14 15:22 UTC, merged

2017-02-14 15:26 UTC, NishiCell commented on common/css/style.css
> +
なるほど、了解です。