1703event feat
miraiken/web pull request #36
Opened 2017-02-15 08:14 UTC by NishiCell

書き換えVer.3

2017-02-15 08:16 UTC, yumetodo requested changes

2017-02-15 08:16 UTC, yumetodo commented on 1703event_feat
> +<!DOCTYPE html>
このファイルは何？

2017-02-15 08:16 UTC, yumetodo commented on event/2017/event_march/exhibition.html
> +  <link rel="stylesheet" href="CSS.css">
CSSの名前と場所がおかしい

2017-02-15 08:16 UTC, yumetodo commented on event/2017/event_march/resource/css
> +
ちゃうねん、``css``っていうディレクトリの中にcssを作ってほしかったんよ

2017-02-15 22:25 UTC, NishiCell commented on event/2017/event_march/resource/css
> +
cssのディレクトリは何処にあるのですか？

2017-02-15 22:25 UTC, NishiCell commented on 1703event_feat
> +<!DOCTYPE html>
？

2017-02-16 04:56 UTC, yumetodo commented on 1703event_feat
> +<!DOCTYPE html>
@NishiCell どこからも参照されてないよね？消そう

2017-02-16 04:58 UTC, yumetodo commented on event/2017/event_march/resource/css
> +
``/event/2017/event_march/resource/css``
そこにCSSファイルを作ってほしかったの。

``/event/2017/event_march/resource``
というディレクトリに``css``というファイルを作って欲しいわけではない。

2017-02-16 05:35 UTC, yumetodo requested changes
結論；落ち着け

2017-02-16 05:35 UTC, yumetodo commented on web/event/2017/event_march/exhibition.html
> +<!DOCTYPE html>
このファイルは何・・・？謎のディレクトリとファイルを量産しないで！

2017-02-16 05:35 UTC, yumetodo commented on event/2017/event_march/resource/css/CSS
> +
拡張子が``css``にするべきなんであって、ファイル名が``css``でどうする・・・

2017-02-16 05:42 UTC, NishiCell commented on web/event/2017/event_march/exhibition.html
> +<!DOCTYPE html>
このファイルとは？

2017-02-16 05:44 UTC, yumetodo commented on web/event/2017/event_march/exhibition.html
> +<!DOCTYPE html>
いやさ、
![image](https://cloud.githubusercontent.com/assets/10869046/23008925/4fe8f29c-f456-11e6-89e6-788872555d17.png)
一度ディレクトリ見てこい、どう考えてもおかしい

2017-02-16 05:45 UTC, yumetodo requested changes

2017-02-16 05:45 UTC, yumetodo commented on event/2017/event_march/resource/css/CSS.css
> +
ディレクトリを眺めればわかるように、ファイル名の命名規則はsnake_caseです。

2017-02-16 05:46 UTC, NishiCell commented on web/event/2017/event_march/exhibition.html
> +<!DOCTYPE html>
（おかしい点が見つからない...）

2017-02-16 05:48 UTC, yumetodo commented on web/event/2017/event_march/exhibition.html
> +<!DOCTYPE html>
ならば問おう。
なんで
``/web/event/2017/event_march``
``/event/2017/event_march``
というダブリがあるのかな？

よくよく自分のファイラーなりで確認すると良い。

2017-02-16 05:51 UTC, NishiCell commented on web/event/2017/event_march/exhibition.html
> +<!DOCTYPE html>
削除し忘れてました。

2017-02-20 01:37 UTC, NishiCell commented on event/2017/event_march/resource/css/CSS.css
> +
他に問題はありますか？

2017-02-24 14:45 UTC, yumetodo commented
なぜに
https://github.com/miraiken/web/commit/d56fc1535481758142ccce5436135b5ec72485f5
と内容的にかぶるものが来るのか、困惑しかない。

2017-02-25 09:05 UTC, closed without merging