fix(2017/event_june/~/exhibition_creater.js) description title
miraiken/web pull request #70
Opened 2017-06-05 05:55 UTC by NishiCell

2017-06-05 06:12 UTC, yumetodo requested changes

2017-06-05 06:12 UTC, yumetodo commented on event/2017/event_june/resource/js/exhibition_creater.js
> +                  "geoscience":"自然のふしぎラボ",
`ふしぎ` がひらがななせいで、その後の `ラボ` に違和感を覚える。というかなんだそのネーミングセンス。

2017-06-05 06:12 UTC, yumetodo commented on event/2017/event_june/resource/js/exhibition_creater.js
> +                  "industrial":"機会のしくみ工場"
もしかして: `s/機会/機械/`

2017-06-05 06:18 UTC, yumetodo commented
しかしこれ、jsonのフォーマット設計ミスだったなぁ・・・。JavaScriptに書いている `description` とか `order` とか `org_id_to_area_id_table_` はjsonに書くべきだったなぁ・・・。

2017-06-05 06:20 UTC, yumetodo commented on event/2017/event_june/resource/js/exhibition_creater.js
> +                  "geoscience":"自然のふしぎラボ",
というかあえて言おう、全般に名前がダサく語呂が悪いと！(難癖

2017-06-05 06:21 UTC, yumetodo commented on event/2017/event_june/resource/js/exhibition_creater.js
> +                  "geoscience":"自然のふしぎラボ",
まあダサいのは私の知ったことじゃないんでいいんですけどね。

2017-06-06 03:43 UTC, NishiCell commented
”機械”を修正した。
妙なネーミングは放置する。

2017-06-06 03:53 UTC, yumetodo approved these changes

2017-06-06 03:53 UTC, merged